from app.models.admin import Permission, Role, RolePermission, User, UserRole
from app.models.audit import AuditLog
from app.models.base import Base
from app.models.documents import (
    DiagnosticDocument,
    DiagnosticExtraction,
    Document,
    DocumentEvent,
    DocumentLink,
    DocumentWorkflowState,
    VehicleDocumentAlert,
    VehicleDocumentAuditField,
    VehicleDocumentPendingAction,
    VehicleDocumentRecord,
    VehicleDocumentRecordTag,
)
from app.models.imports import ImportBatch, ImportError, ImportFile, ImportMapping, ImportRawRow
from app.models.incidents import Incident, IncidentEvent, IncidentEvidence
from app.models.integrations import EmailIntake, EmailIntakeAttachment
from app.models.management_center import (
    ClaimIncident,
    ClaimRefstroLine,
    ClaimRentwayAR,
    ManagementAction,
    ManagementEvidence,
    ManagementHistory,
    ManagementProcess,
    ManagementProcessAssociation,
    ManagementProcessType,
    ManagementRule,
)
from app.models.organization import OrganizationalUnit, Team, TeamMember, UserOrganizationalUnit
from app.models.pilot import PilotFeedback
from app.models.portal import (
    PortalInvitation,
    PortalOrganization,
    PortalPublicationAccess,
    PortalUser,
)
from app.models.settings import SettingsCatalog, SettingsValue
from app.models.tasks import (
    QuickRecord,
    Task,
    TaskComment,
    TaskDocument,
    TaskEmailOrigin,
    TaskGuidedFlowRun,
    TaskGuidedFlowStepRun,
    TaskHelpRequest,
    TaskHistory,
    TaskParticipant,
)
from app.models.vehicles import (
    Vehicle,
    VehicleExternalSnapshot,
    VehicleFinancialPlan,
    VehicleIdentifier,
    VehicleLifecycleEvent,
    VehicleManualField,
    VehicleOperationalStatusEvent,
)
from app.models.vehicle_sales import (
    VehicleImage,
    VehicleSaleLead,
    VehicleSaleProfile,
    VehicleSalePublication,
)
from app.models.vehicle_history_audit import (
    VehicleHistoryAudit,
    VehicleHistoryAuditDocument,
    VehicleHistoryAuditIssue,
    VehicleHistoryAuditReading,
    VehicleHistoryAuditRule,
    VehicleHistoryAuditService,
    VehicleHistoryAuditTruth,
)
from app.models.workshop import (
    WorkshopProcess,
    WorkshopProcessEvidence,
    WorkshopProcessNote,
    WorkshopProcessService,
    WorkshopTechnicalReading,
)
from app.models.workshop_phased import (
    WorkshopDiagnosticCatalogItem,
    WorkshopDiagnosticSuggestion,
    WorkshopMaterialNeed,
    WorkshopPhasedClosureCheck,
    WorkshopPhasedProcess,
    WorkshopPhasedProcessAlert,
    WorkshopPhasedProcessPhase,
    WorkshopPhasedProcessService,
    WorkshopPhasedTechnicalCheck,
    WorkshopPhasedTechnicalIncident,
    WorkshopPhasedTechnicalReport,
    WorkshopPublicCounter,
    WorkshopTemplate,
    WorkshopTemplateVersion,
)

__all__ = [
    "AuditLog",
    "Base",
    "ClaimIncident",
    "ClaimRefstroLine",
    "ClaimRentwayAR",
    "Document",
    "DiagnosticDocument",
    "DiagnosticExtraction",
    "DocumentEvent",
    "DocumentLink",
    "DocumentWorkflowState",
    "VehicleDocumentAlert",
    "VehicleDocumentAuditField",
    "VehicleDocumentPendingAction",
    "VehicleDocumentRecord",
    "VehicleDocumentRecordTag",
    "EmailIntake",
    "EmailIntakeAttachment",
    "Incident",
    "IncidentEvent",
    "IncidentEvidence",
    "ImportBatch",
    "ImportError",
    "ImportFile",
    "ImportMapping",
    "ImportRawRow",
    "ManagementAction",
    "ManagementEvidence",
    "ManagementHistory",
    "ManagementProcess",
    "ManagementProcessAssociation",
    "ManagementProcessType",
    "ManagementRule",
    "OrganizationalUnit",
    "Permission",
    "PilotFeedback",
    "PortalInvitation",
    "PortalOrganization",
    "PortalPublicationAccess",
    "PortalUser",
    "QuickRecord",
    "Role",
    "RolePermission",
    "SettingsCatalog",
    "SettingsValue",
    "Task",
    "TaskComment",
    "TaskDocument",
    "TaskEmailOrigin",
    "TaskGuidedFlowRun",
    "TaskGuidedFlowStepRun",
    "TaskHelpRequest",
    "TaskHistory",
    "TaskParticipant",
    "Team",
    "TeamMember",
    "User",
    "UserOrganizationalUnit",
    "UserRole",
    "Vehicle",
    "VehicleExternalSnapshot",
    "VehicleFinancialPlan",
    "VehicleImage",
    "VehicleSaleLead",
    "VehicleSaleProfile",
    "VehicleSalePublication",
    "VehicleHistoryAudit",
    "VehicleHistoryAuditDocument",
    "VehicleHistoryAuditIssue",
    "VehicleHistoryAuditReading",
    "VehicleHistoryAuditRule",
    "VehicleHistoryAuditService",
    "VehicleHistoryAuditTruth",
    "VehicleIdentifier",
    "VehicleLifecycleEvent",
    "VehicleManualField",
    "VehicleOperationalStatusEvent",
    "WorkshopProcess",
    "WorkshopProcessEvidence",
    "WorkshopProcessNote",
    "WorkshopProcessService",
    "WorkshopTechnicalReading",
    "WorkshopDiagnosticCatalogItem",
    "WorkshopDiagnosticSuggestion",
    "WorkshopMaterialNeed",
    "WorkshopPhasedClosureCheck",
    "WorkshopPhasedProcess",
    "WorkshopPhasedProcessAlert",
    "WorkshopPhasedProcessPhase",
    "WorkshopPhasedProcessService",
    "WorkshopPhasedTechnicalCheck",
    "WorkshopPhasedTechnicalIncident",
    "WorkshopPhasedTechnicalReport",
    "WorkshopPublicCounter",
    "WorkshopTemplate",
    "WorkshopTemplateVersion",
]
